spring.config.import=optional:file:.env[.properties]

spring.application.name=productos-service
server.port=${SERVER_PORT:8082}

# Base de datos (RDS)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Validación JWT (Azure AD)
app.security.issuer=${AZURE_ISSUER}
app.security.jwk-set-uri=${AZURE_JWKS_URI}
app.security.audiences=${AZURE_AUDIENCES}
app.security.required-scope=${AZURE_REQUIRED_SCOPE:access_as_user}

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}