spring.application.name=login-service
server.port=${SERVER_PORT:8081}

# Base de datos (PostgreSQL o H2 por defecto)
spring.datasource.url=${DB_URL:jdbc:h2:mem:logindb}
spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.h2.console.enabled=true

# Hibernate / JPA
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

